// GENERATED by scripts/codegen_ada_ext_cpp.py from
// design_and_analysis_extension.schema.json — DO NOT EDIT. Run `pixi run json-code-gen-cpp`.
// ADA Design and Analysis Extension; schema version 1.2.0.
#pragma once

#include <optional>
#include <sstream>
#include <string>
#include <vector>

namespace adacpp::ada_ext {

// Schema version this header was generated from. The producer stamps it into ADA_EXT_data.version so
// a consumer (viewer) / the drift test can detect a schema change as a version mismatch, not a crash.
inline constexpr const char *kSchemaVersion = "1.2.0";

// ADA Design and Analysis Extension (the glTF ``ADA_EXT_data`` extension). Default = a STEP import: empty design/sim
// arrays, the schema version, null assembly_guid. The design/simulation array items are opaque
// pre-serialized JSON strings (the native path never populates them) — push a serialized object.
struct AdaDesignAndAnalysisExtension {
    std::vector<std::string> simulation_objects;
    std::vector<std::string> design_objects;
    std::string version = "1.2.0";
    std::optional<std::string> assembly_guid;

    std::string to_json() const {
        auto arr = [](const std::vector<std::string> &v) {
            std::string s = "[";
            for (size_t i = 0; i < v.size(); ++i) {
                if (i)
                    s += ",";
                s += v[i];
            }
            return s + "]";
        };
        auto str = [](const std::string &s) { return "\"" + s + "\""; };
        auto opt = [](const std::optional<std::string> &o) { return o ? ("\"" + *o + "\"") : std::string("null"); };
        std::ostringstream o;
        o << "{\"simulation_objects\":" << arr(simulation_objects);
        o << ",\"design_objects\":" << arr(design_objects);
        o << ",\"version\":" << str(version);
        o << ",\"assembly_guid\":" << opt(assembly_guid);
        o << "}";
        return o.str();
    }
};

} // namespace adacpp::ada_ext
