name: ada-cpp
channels:
  - conda-forge
dependencies:
  - occt ==7.7.0
  - nanobind ==1.2.0
  - pytest ==7.3.1
  - scikit-build-core ==0.3.3
  - cmake ==3.26.3
  - numpy ==1.24.3
  - cgal-cpp
  - nomkl
  - boa ==0.15.1