name: ada-cpp
channels:
  - conda-forge
dependencies:
  - occt ==7.7.1=*novtk*
  - nanobind ==1.4.0
  - pytest ==7.3.1
  - scikit-build-core ==0.4.7
  - cmake ==3.26.3
  - numpy ==1.24.3
  - cgal-cpp
  - nomkl
  - boa ==0.15.1