name: ada-cpp
channels:
  - krande/label/dev
  - conda-forge
dependencies:
  - occt ==7.7.2=*novtk*
  - ifcopenshell
  - nanobind ==1.5.2
  - pytest ==7.3.1
  - scikit-build-core ==0.4.7
  - cmake ==3.26.3
  - numpy
  - cgal-cpp
  - nomkl
  - boa ==0.15.1
  - tinygltf ==2.8.13
  - gmsh
  - gtest