occt:
  - 7.7.2=*novtk*
  - 7.7.2=*all*

c_stdlib_version:          # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]

c_compiler:
  - vs2022  # [win]

cxx_compiler:
  - vs2022  # [win]