{% set name = 'ada-cpp' %}
{% set data = load_setup_py_data() %}
{% set version = load_file_data('pyproject.toml')["project"]["version"] %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  skip: True  # [py<310]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libGL-devel') }}  # [linux]
    - cmake
    - ninja   # [win]
    - make    # [unix]

  host:
    - python
    - occt * *{{ variant }}*
    - ifcopenshell
    - cgal-cpp
    - scikit-build-core
    - nanobind
    - cli11
    - tinygltf
    - gmsh
    - pip

  run:
    - python
    - "{{ pin_compatible('gmsh', max_pin='x.x.x') }}"

test:
  source_files:
    - tests
    - files
  requires:
    - pytest
    - ada-py
  commands:
    - pytest tests

about:
  home: https://github.com/Krande/adacpp
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A module with drop-in replacement functions for ada-py written in c++ to improve performance."

extra:
  recipe-maintainers:
    - Krande
