{% set name = 'ada-cpp' %}
{% set data = load_setup_py_data() %}
{% set version = load_file_data('pyproject.toml')["project"]["version"] %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  number: 1

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ cdt('mesa-libGL-devel') }}" # [unix] provides OpenGL development libraries

  host:
    - python
    - occt
    - pybind11-stubgen 2.1
    - ifcopenshell
    - cgal-cpp
    - scikit-build-core
    - nanobind
    - cli11
    - tinygltf
    - gmsh
    - pip

  run:
    - python
    - "{{ pin_compatible('occt', max_pin='x.x.x') }}"
    - "{{ pin_compatible('gmsh', max_pin='x.x.x') }}"
    - "{{ pin_compatible('ifcopenshell', max_pin='x.x.x') }}"

test:
  source_files:
    - tests
    - files
  requires:
    - pytest
  commands:
    - pytest tests

about:
  home: https://github.com/Krande/adacpp
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "A module with drop-in replacement functions for ada-py written in c++ to improve performance."

extra:
  recipe-maintainers:
    - Krande
