"""Generate ``src/adacpp/cad/__init__.py`` from the compiled extension.

WHY. That module re-exports the C++ ``cad`` bindings into Python, and it was
maintained by hand as TWO parallel lists (``name = _cad.name`` assignments and a
separate ``__all__``). Both rot, and both had:

  * 15 names were assigned but missing from ``__all__`` (``ifc_taxonomy_settings``,
    ``stream_ifc_to_glb``, ``step_emit_ifc_brep``, the meshopt codecs, ...), so
    ``from adacpp.cad import *`` silently omitted working functions;
  * ``glb_diff`` was re-exported UNGUARDED after its C++ binding was compiled out
    of the wasm build — which makes ``import adacpp.cad`` raise AttributeError and
    take the whole module down on wasm/pyodide;
  * a new binding stayed invisible from Python until someone remembered to edit
    two places (this cost real debugging time when ``tess_tracks`` landed).

WHAT IT EMITS. Explicit ``name = _cad.name`` assignments and an explicit
``__all__`` — no star imports, no ``globals()`` injection, so the module stays
statically analysable and IDE-completable. Generation only removes the *copying*,
not the explicitness.

CONDITIONAL BINDINGS. Some bindings are compiled only in the native build
(``#ifndef __EMSCRIPTEN__`` in cad_py_wrap.cpp). Those are emitted via
``_optional()``, which binds a stub that raises ``NotImplementedError`` naming the
reason when called. The set is derived by parsing the guards out of the C++ rather
than hardcoded here, so a newly-guarded binding is handled without editing this file.

Why a stub and not a ``hasattr`` guard: the stub keeps the name bound and keeps
``__all__`` IDENTICAL across native and wasm, so the module's Python surface is a
build-independent constant. A guard instead makes the name vanish, turning a
missing binding into a bare ``AttributeError`` at some unrelated call site with no
hint as to why. Failing at the call, with a reason, beats failing at import (which
takes the whole package down) or failing mutely.

USAGE
    pixi run gen-cad-api          # regenerate (requires the ext to be built)

The companion test (tests/test_cad_api_generated.py) fails if the checked-in file
does not match what this would emit, so drift is caught in CI rather than by a
user hitting an AttributeError.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

_HERE = pathlib.Path(__file__).resolve().parent
_ROOT = _HERE.parent
_WRAP = _ROOT / "src" / "cad" / "cad_py_wrap.cpp"
_OUT = _ROOT / "src" / "adacpp" / "cad" / "__init__.py"

# Why a binding may be absent, keyed by name. Only for cases where a curated sentence beats the
# generic one — e.g. naming the browser's replacement so the reader knows what to reach for. A name
# with no entry falls back to _GENERIC_REASON, so adding a guard in C++ never breaks generation.
_REASONS = {
    "glb_diff": "native-only (mmap/POSIX-backed); the browser build provides GLB-diff via the standalone adacpp_glb_diff embind module",
}
_GENERIC_REASON = "compiled out of this build (guarded by #ifndef __EMSCRIPTEN__ in cad_py_wrap.cpp)"

_HEADER = '''"""Backend-agnostic CAD operations.

This module is the future home of the CadBackend abstraction that will let
adapy swap between pythonocc-core and adacpp implementations.

The Python surface here is the SAME on the native and wasm/pyodide builds: every
name below is always bound and always in ``__all__``. The underlying C++ diverges
by which kernel is available, and a few entry points are compiled out of the wasm
build entirely — those bind to a stub via :func:`_optional` that raises when
called, rather than vanishing.

GENERATED by tools/gen_cad_api.py from the compiled ``cad`` extension — do not
edit by hand. Regenerate with ``pixi run gen-cad-api`` after adding a binding;
tests/py/test_cad_api_generated.py fails if this file drifts from the extension.

It was previously two hand-maintained lists (assignments + ``__all__``) which had
already diverged by 15 names, and re-exported ``glb_diff`` unconditionally after
its binding was compiled out of the wasm build — an AttributeError at *import*
that took the whole ``adacpp`` package down under pyodide, and with it
``ada.cad.select_backend()``, so a caller could not reach the operations that were
present.
"""

from .._ada_cpp_ext_impl import cad as _cad


def _optional(name: str, reason: str):
    """Bind a symbol this build may not register.

    A plain ``x = _cad.x`` raises AttributeError at *import* time when the binding
    is compiled out, taking the whole package down. Returning a stub defers the
    failure to the call, where it can say what is actually wrong.
    """
    attr = getattr(_cad, name, None)
    if attr is not None:
        return attr

    def _unavailable(*_args, **_kwargs):
        raise NotImplementedError(f"adacpp.cad.{name} is not available in this build: {reason}")

    _unavailable.__name__ = name
    _unavailable.__doc__ = f"Unavailable in this build: {reason}"
    return _unavailable


'''


def native_only_bindings(wrap_src: str) -> set[str]:
    """Binding names compiled only in the native build (inside ``#ifndef __EMSCRIPTEN__``).

    Tracks nesting so an inner ``#if`` doesn't end the guard early.
    """
    out: set[str] = set()
    lines = wrap_src.splitlines()
    depth = 0
    in_guard = False
    guard_depth = 0
    for i, line in enumerate(lines):
        st = line.strip()
        if st.startswith("#if"):
            depth += 1
            if st.startswith("#ifndef") and "__EMSCRIPTEN__" in st:
                in_guard, guard_depth = True, depth
        elif st.startswith("#endif"):
            if in_guard and depth == guard_depth:
                in_guard = False
            depth -= 1
        if in_guard and "m.def(" in line:
            m = re.search(r'"([A-Za-z_][A-Za-z_0-9]*)"', line)
            if not m and i + 1 < len(lines):
                m = re.search(r'"([A-Za-z_][A-Za-z_0-9]*)"', lines[i + 1])
            if m:
                out.add(m.group(1))
    return out


def render(names: list[str], optional: set[str]) -> str:
    """Emit the module: one explicit assignment per name, then one explicit ``__all__``.

    ``names`` must already include the optional ones — they are bound too, just via a stub, so the
    surface does not depend on the build target.
    """
    always = [n for n in names if n not in optional]
    opt = [n for n in names if n in optional]
    body = [_HEADER]
    body.append("\n".join(f"{n} = _cad.{n}" for n in always))
    body.append("\n")
    if opt:
        body.append(
            "\n# Compiled only in the native build (the #ifndef __EMSCRIPTEN__ guards in\n"
            "# cad_py_wrap.cpp). Bound to a stub rather than skipped, so this module's surface and\n"
            "# __all__ are the same on every target and the failure lands at the call with a reason.\n"
        )
        for n in opt:
            reason = _REASONS.get(n, _GENERIC_REASON)
            # Emit the exploded form WITH a trailing comma ("magic trailing comma"): black keeps a
            # call like this one-arg-per-line no matter how short, so this output is already
            # black-canonical and `pixi run lint` is a no-op on it. Emitting the one-liner instead
            # means black rewraps whenever a reason pushes past the line length, and the reformatted
            # file then no longer matches generate() — the staleness test fails and the fix looks
            # like "regenerate", which does not help because black just rewraps it again. A
            # generated file and a formatter cannot both own the layout; this hands it to black.
            body.append(f'{n} = _optional(\n    "{n}",\n    "{reason}",\n)\n')
    body.append("\n__all__ = [\n")
    body.extend(f'    "{n}",\n' for n in sorted(always + opt))
    body.append("]\n")
    return "".join(body)


def generate() -> str:
    try:
        from adacpp._ada_cpp_ext_impl import cad as _cad
    except ImportError as exc:  # pragma: no cover
        raise SystemExit(f"build the extension first (pixi run build-dist): {exc}") from exc
    names = sorted(n for n in dir(_cad) if not n.startswith("_"))
    optional = native_only_bindings(_WRAP.read_text(encoding="utf-8"))
    # Generation must read a NATIVE build: it is the only one with the full surface. Generating from a
    # wasm build would silently emit a module missing every native-only name, and since the wasm build
    # cannot see them, nothing downstream would notice. Fail loudly instead.
    absent = sorted(optional - set(names))
    if absent:
        raise SystemExit(
            f"cannot generate: {absent} are guarded #ifndef __EMSCRIPTEN__ in {_WRAP.name} but missing "
            f"from the loaded extension. Generate from a native build (pixi run build-dist), not a wasm "
            f"one. If a binding was deleted from C++, drop its guard too."
        )
    return render(names, optional)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if the checked-in file is stale")
    args = ap.parse_args()
    new = generate()
    # Always utf-8: the emitted module and the C++ it is derived from both contain
    # non-ASCII, and read_text/write_text otherwise follow the platform default —
    # cp1252 on Windows, which silently rewrites every em-dash to U+FFFD. That
    # corrupts the file on write and makes --check compare against a mangled read.
    if args.check:
        cur = _OUT.read_text(encoding="utf-8") if _OUT.exists() else ""
        if cur != new:
            print(f"{_OUT} is STALE — run `pixi run gen-cad-api`", file=sys.stderr)
            return 1
        print(f"{_OUT} is up to date")
        return 0
    _OUT.write_text(new, encoding="utf-8")
    print(f"wrote {_OUT} ({len(new.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
