"""Backend-agnostic CAD operations.

This module is the future home of the CadBackend abstraction that will let
adapy swap between pythonocc-core and adacpp implementations.

The Python surface here is the SAME on the native and wasm/pyodide builds: every
name below is always bound and always in ``__all__``. The underlying C++ diverges
by which kernel is available, and a few entry points are compiled out of the wasm
build entirely — those bind to a stub via :func:`_optional` that raises when
called, rather than vanishing.

GENERATED by tools/gen_cad_api.py from the compiled ``cad`` extension — do not
edit by hand. Regenerate with ``pixi run gen-cad-api`` after adding a binding;
tests/py/test_cad_api_generated.py fails if this file drifts from the extension.

It was previously two hand-maintained lists (assignments + ``__all__``) which had
already diverged by 15 names, and re-exported ``glb_diff`` unconditionally after
its binding was compiled out of the wasm build — an AttributeError at *import*
that took the whole ``adacpp`` package down under pyodide, and with it
``ada.cad.select_backend()``, so a caller could not reach the operations that were
present.
"""

from .._ada_cpp_ext_impl import cad as _cad


def _optional(name: str, reason: str):
    """Bind a symbol this build may not register.

    A plain ``x = _cad.x`` raises AttributeError at *import* time when the binding
    is compiled out, taking the whole package down. Returning a stub defers the
    failure to the call, where it can say what is actually wrong.
    """
    attr = getattr(_cad, name, None)
    if attr is not None:
        return attr

    def _unavailable(*_args, **_kwargs):
        raise NotImplementedError(f"adacpp.cad.{name} is not available in this build: {reason}")

    _unavailable.__name__ = name
    _unavailable.__doc__ = f"Unavailable in this build: {reason}"
    return _unavailable


AdvancedFaceData = _cad.AdvancedFaceData
Color = _cad.Color
GroupReference = _cad.GroupReference
IfcNgeomStream = _cad.IfcNgeomStream
Mesh = _cad.Mesh
MeshType = _cad.MeshType
PcurveData = _cad.PcurveData
ShapeHandle = _cad.ShapeHandle
StepNgeomStream = _cad.StepNgeomStream
StepRootMeta = _cad.StepRootMeta
StepShapeData = _cad.StepShapeData
area = _cad.area
bbox = _cad.bbox
blobs_to_ifc = _cad.blobs_to_ifc
boolean = _cad.boolean
build_advanced_face_bspline = _cad.build_advanced_face_bspline
build_advanced_face_conical = _cad.build_advanced_face_conical
build_advanced_face_cylindrical = _cad.build_advanced_face_cylindrical
build_advanced_face_planar = _cad.build_advanced_face_planar
build_advanced_face_surface_of_linear_extrusion = _cad.build_advanced_face_surface_of_linear_extrusion
build_advanced_face_surface_of_revolution = _cad.build_advanced_face_surface_of_revolution
build_advanced_face_toroidal = _cad.build_advanced_face_toroidal
build_box = _cad.build_box
build_bspline_surface_face = _cad.build_bspline_surface_face
build_cone = _cad.build_cone
build_cylinder = _cad.build_cylinder
build_extruded_area_solid = _cad.build_extruded_area_solid
build_extruded_area_solid_tapered = _cad.build_extruded_area_solid_tapered
build_face_based_surface_model = _cad.build_face_based_surface_model
build_filled_face = _cad.build_filled_face
build_fixed_reference_swept_area_solid = _cad.build_fixed_reference_swept_area_solid
build_planar_face = _cad.build_planar_face
build_revolved_area_solid = _cad.build_revolved_area_solid
build_sphere = _cad.build_sphere
build_swept_disk_solid = _cad.build_swept_disk_solid
build_wire = _cad.build_wire
center_of_mass = _cad.center_of_mass
cut_surfaces = _cad.cut_surfaces
distance = _cad.distance
edges = _cad.edges
extrude_face_along_normal = _cad.extrude_face_along_normal
face_id = _cad.face_id
face_plane = _cad.face_plane
face_surface_type = _cad.face_surface_type
face_to_advanced_face = _cad.face_to_advanced_face
faces = _cad.faces
free_faces = _cad.free_faces
from_topods_pointer = _cad.from_topods_pointer
ifc_taxonomy_settings = _cad.ifc_taxonomy_settings
is_valid = _cad.is_valid
loft_profiles = _cad.loft_profiles
make_box = _cad.make_box
make_cylinder = _cad.make_cylinder
make_halfspace = _cad.make_halfspace
make_sphere = _cad.make_sphere
make_volumes_from_faces = _cad.make_volumes_from_faces
make_wire = _cad.make_wire
merge_cells = _cad.merge_cells
mesh_spike_stats = _cad.mesh_spike_stats
meshopt_decode_index_sequence = _cad.meshopt_decode_index_sequence
meshopt_decode_vertex_buffer = _cad.meshopt_decode_vertex_buffer
meshopt_encode_index_sequence = _cad.meshopt_encode_index_sequence
meshopt_encode_vertex_buffer = _cad.meshopt_encode_vertex_buffer
meshopt_simplify_mesh = _cad.meshopt_simplify_mesh
non_manifold_merge = _cad.non_manifold_merge
obb = _cad.obb
point_in_solid = _cad.point_in_solid
polygon_face = _cad.polygon_face
read_step_bytes = _cad.read_step_bytes
read_step_shapes = _cad.read_step_shapes
section_with_plane = _cad.section_with_plane
serialize = _cad.serialize
serialize_brep = _cad.serialize_brep
sew_faces = _cad.sew_faces
shape_type = _cad.shape_type
shells = _cad.shells
solids = _cad.solids
step_emit_ifc_brep = _cad.step_emit_ifc_brep
step_parity = _cad.step_parity
stream_ifc_to_glb = _cad.stream_ifc_to_glb
stream_ifc_to_step = _cad.stream_ifc_to_step
stream_step_to_glb = _cad.stream_step_to_glb
stream_step_to_glb_st = _cad.stream_step_to_glb_st
stream_step_to_ifc = _cad.stream_step_to_ifc
stream_step_to_mesh = _cad.stream_step_to_mesh
stream_step_to_meshes = _cad.stream_step_to_meshes
stream_step_to_ngeom = _cad.stream_step_to_ngeom
stream_step_to_step = _cad.stream_step_to_step
tess_tracks = _cad.tess_tracks
tessellate = _cad.tessellate
tessellate_batch = _cad.tessellate_batch
tessellate_box = _cad.tessellate_box
tessellate_stream = _cad.tessellate_stream
to_topods_pointer = _cad.to_topods_pointer
transform = _cad.transform
unify_coplanar_faces = _cad.unify_coplanar_faces
vertex_points = _cad.vertex_points
volume = _cad.volume
wire_points = _cad.wire_points
wires = _cad.wires
write_glb_bytes = _cad.write_glb_bytes
write_step = _cad.write_step

# Compiled only in the native build (the #ifndef __EMSCRIPTEN__ guards in
# cad_py_wrap.cpp). Bound to a stub rather than skipped, so this module's surface and
# __all__ are the same on every target and the failure lands at the call with a reason.
glb_diff = _optional("glb_diff", "native-only (mmap/POSIX-backed); the browser build provides GLB-diff via the standalone adacpp_glb_diff embind module")

__all__ = [
    "AdvancedFaceData",
    "Color",
    "GroupReference",
    "IfcNgeomStream",
    "Mesh",
    "MeshType",
    "PcurveData",
    "ShapeHandle",
    "StepNgeomStream",
    "StepRootMeta",
    "StepShapeData",
    "area",
    "bbox",
    "blobs_to_ifc",
    "boolean",
    "build_advanced_face_bspline",
    "build_advanced_face_conical",
    "build_advanced_face_cylindrical",
    "build_advanced_face_planar",
    "build_advanced_face_surface_of_linear_extrusion",
    "build_advanced_face_surface_of_revolution",
    "build_advanced_face_toroidal",
    "build_box",
    "build_bspline_surface_face",
    "build_cone",
    "build_cylinder",
    "build_extruded_area_solid",
    "build_extruded_area_solid_tapered",
    "build_face_based_surface_model",
    "build_filled_face",
    "build_fixed_reference_swept_area_solid",
    "build_planar_face",
    "build_revolved_area_solid",
    "build_sphere",
    "build_swept_disk_solid",
    "build_wire",
    "center_of_mass",
    "cut_surfaces",
    "distance",
    "edges",
    "extrude_face_along_normal",
    "face_id",
    "face_plane",
    "face_surface_type",
    "face_to_advanced_face",
    "faces",
    "free_faces",
    "from_topods_pointer",
    "glb_diff",
    "ifc_taxonomy_settings",
    "is_valid",
    "loft_profiles",
    "make_box",
    "make_cylinder",
    "make_halfspace",
    "make_sphere",
    "make_volumes_from_faces",
    "make_wire",
    "merge_cells",
    "mesh_spike_stats",
    "meshopt_decode_index_sequence",
    "meshopt_decode_vertex_buffer",
    "meshopt_encode_index_sequence",
    "meshopt_encode_vertex_buffer",
    "meshopt_simplify_mesh",
    "non_manifold_merge",
    "obb",
    "point_in_solid",
    "polygon_face",
    "read_step_bytes",
    "read_step_shapes",
    "section_with_plane",
    "serialize",
    "serialize_brep",
    "sew_faces",
    "shape_type",
    "shells",
    "solids",
    "step_emit_ifc_brep",
    "step_parity",
    "stream_ifc_to_glb",
    "stream_ifc_to_step",
    "stream_step_to_glb",
    "stream_step_to_glb_st",
    "stream_step_to_ifc",
    "stream_step_to_mesh",
    "stream_step_to_meshes",
    "stream_step_to_ngeom",
    "stream_step_to_step",
    "tess_tracks",
    "tessellate",
    "tessellate_batch",
    "tessellate_box",
    "tessellate_stream",
    "to_topods_pointer",
    "transform",
    "unify_coplanar_faces",
    "vertex_points",
    "volume",
    "wire_points",
    "wires",
    "write_glb_bytes",
    "write_step",
]
