name: ci-tests

# bump 1
on:
  workflow_dispatch:

  push:

# Use concurrency to ensure that only one instance of this workflow is running at a time
concurrency:
  group: ci-tests-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CROOT_DIR: /home/runner/work/build
  ARTIFACTS_DIR: /home/runner/work/artifacts
  PKG_DIR: linux-64

jobs:

  build_test:
    name: ada-cpp-test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      # Install OpenGL dependencies
      - name: Install OpenGL dependencies
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev

      - uses: prefix-dev/setup-pixi@v0.8.14
        with:
          pixi-version: v0.41.3
          environments: test
          cache: true

      - name: install package
        run: |
          pixi run pytest