name: ci-ada-cpp-test

# bump 1
on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - .github/workflows/basic_test.yaml

jobs:
  build_test:
    name: ada-cpp-${{ matrix.platform.name }}-${{ matrix.pyver.name }}
    runs-on: ${{ matrix.platform.distver }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        pyver: [
          { name: py311, distver: '3.11' },
        ]
        platform: [
          { name: win, distver: windows-latest, pkg_dir: 'win-64' },
          { name: linux, distver: ubuntu-latest, pkg_dir: 'linux-64' },
          { name: macOS, distver: macos-latest, pkg_dir: 'osx-64' }
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Download and extract MacOSX SDK
        if: ${{ matrix.platform.name == 'macOS' }}
        run: |
          curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.15.sdk.tar.xz | tar -xvJf - -C /Users/runner/work/

      - name: Install ninja
        run: |
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            sudo apt-get install ninja-build
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            brew install ninja
          elif [[ "$OSTYPE" == "win32" ]]; then
            choco install ninja
          fi
      - uses: mamba-org/setup-micromamba@v1 # https://github.com/mamba-org/setup-micromamba
        with:
          environment-file: environment.build.yml
          create-args: >-
            python=${{ matrix.pyver.distver }}
            anaconda-client

      - name: create dist dir
        run: |
          mkdir -p ${{ github.workspace }}/dist

      - name: build local packages
        run: |
          boa build conda --python ${{ matrix.pyver.distver }} -m ./conda/conda_build_config.yaml --no-remove-work-dir --output-folder '${{ github.workspace }}/dist'

      # list files in dist dir for windows
      - name: list files in dist dir
        if: ${{ matrix.platform.name == 'win' }}
        run: |
          ls -l ${{ github.workspace }}/dist/${{ matrix.platform.pkg_dir }}

      - name: upload to anaconda
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force --user krande --label dev '${{ github.workspace }}/dist/${{ matrix.platform.pkg_dir }}/*.tar.bz2'
